/* Main.ino file generated by New Project wizard
 *
 * Created:   Sun May 10 2020
 * Processor: ATmega328P
 * Compiler:  Arduino AVR
 * Source Code: RGB Lighting Control
 */
#include <SoftwareSerial.h>
#include "TrafficLight.h"
#include "PID.h"
const int readSensorPin = 6;
const int transmitSensorPin = 3;
int ifRead;
unsigned int carCount = 0;
unsigned long currentTime = 0;
unsigned long timeSinceArduinoTurnedOn = 0;
unsigned long detectedTime = 0;
unsigned long previousDetectedTime = 0;
unsigned long timeError = 0;
unsigned long timeDelay = 0;
unsigned long previousTime = 0;
unsigned long timeSinceGreen = 0;
unsigned long timeSinceYellow = 0;
bool runOnce[5] = { true,true,true,true,true};
String string = "Number Of Objects Detected: "+carCount;
String msg = "";
bool targetDetected = false;
bool enterSystem = false;
TrafficLight lightNorth;
PID pidController;
void setup()
 { // put your setup code here, to run once:
  Serial.begin(9600);
  pinMode(readSensorPin,INPUT);
  pinMode(transmitSensorPin,OUTPUT);
  lightNorth.setLightPinOut(OUTPUT, 11, 10, 9);
  lightNorth.directionState = lightNorth.NORTH;
  lightNorth.lightState = lightNorth.FLASHINGRED;
  tone(3, 38000);
 }

void loop()
{ // put your main code here, to run repeatedly:
	msg = "";
	timeSinceArduinoTurnedOn = millis();
	// check for data byte on USB serial port
	if (Serial.available())
	{
		// get byte from USB serial port
		while (Serial.available())
		{
			msg = Serial.readString();// read the incoming data as string
		}
		if (msg == "Hello")
		{
			//Send data to usb serial port
			Serial.write(" \nWelcome to Street Smart Traffic Lighting System !");
			Serial.write(" \nEntering System...");
			Serial.write(" \nPlease Wait...");
		}
		if (msg == "2682209")
		{
			Serial.write("SUCCESS");
			enterSystem = true;
			previousTime = millis();

		}
		if (msg == "QUIT")
		{
			Serial.write("QUIT");
			enterSystem = false;
		}
		
	}
	else { Serial.flush();}


	if (enterSystem)
	{
		currentTime = millis();

		// Car Detection
		delay(100);
		ifRead = digitalRead(readSensorPin);
		if (ifRead == LOW)
		{
			targetDetected = true;
			detectedTime = millis();
		}
		else { targetDetected = false; }

		if (targetDetected && lightNorth.lightState == lightNorth.GREEN)
		{
			carCount += 1;
			string = "Car Count:" + (String)carCount;
			Serial.print(string);
			targetDetected = false;
		}

		if (currentTime - previousTime > 2000 && runOnce[0])
		{
			Serial.write("NORTHGREEN");
			lightNorth.lightState = lightNorth.GREEN;
			timeSinceGreen = currentTime;
			runOnce[0] = false;

		}
		
		if (currentTime - previousTime > 2000)
		{
			if (carCount >= pidController.getTargetCarCount() || (currentTime - timeSinceGreen >= pidController.getTargetTimeValue()))
			{
				if (runOnce[1])
				{
					lightNorth.lightState = lightNorth.YELLOW;
					Serial.write("NORTHYELLOW");
					timeSinceYellow = currentTime;
					runOnce[1] = false;
				}
				if (!runOnce[1] && currentTime - timeSinceYellow > 2000)
				{
					lightNorth.lightState = lightNorth.RED;
					if (runOnce[2])
					{
						Serial.write("NORTHRED");
						runOnce[2] = false;
					}
				}
			}
		}
		lightNorth.TrafficLightControl(currentTime, 1000);
		runOnce[3] = true;
	}
	else
	{
		lightNorth.lightState = lightNorth.FLASHINGRED;
		lightNorth.TrafficLightControl(timeSinceArduinoTurnedOn, 1000);
	}
	
}
	
